products:
  file_type: products
  input_path: ./data/raw/products.csv
  output_path: ./output/clean/products
  schema:
    product_id: string
    product_name: string
    category: string
  null_check:
    columns: "all"
    null_path: ./data_quality/nulls/products
  dup_check:
    columns: ["product_id"]
    dup_path: ./data_quality/duplicates/products

stores:
  file_type: stores
  input_path: ./data/raw/stores.csv
  output_path: ./output/clean/stores
  schema:
    store_id: string
    store_name: string
    location: string
  null_check:
    columns: "all"
    null_path: ./data_quality/nulls/stores
  dup_check:
    columns: ["store_id"]
    dup_path: ./data_quality/duplicates/stores

sales:
  file_type: sales
  input_path: ./data/raw/sales.csv
  output_path: ./output/clean/sales
  schema:
    transaction_id: string
    store_id: string
    product_id: string
    quantity: int
    transaction_date: date
    price: double
  null_check:
    columns: "all"
    null_path: ./data_quality/nulls/sales
  dup_check:
    columns: ["transaction_id"]
    dup_path: ./data_quality/duplicates/sales


clean_paths:
  sales: ./output/clean/sales
  products: ./output/clean/products
  stores: ./output/clean/stores
output_paths:
  enriched: ./output/enriched
  kpi: ./output/metrics/

